/**
 * Created by nathan on 1/13/17.
 * just for fun
 */
object Bullshit {

  def getBullshit: String = {

    def getBS(a: Array[String]): String = a(scala.util.Random.nextInt(a.length))

    getBS(verbs) + " " + getBS(adjectives) + " " + getBS(nouns)

  }

  private val verbs = Array(
    "activating",
    "aggregating",
    "architecting",
    "benchmarking",
    "branding",
    "cultivating",
    "delivering",
    "deploying",
    "disintermediating",
    "driving",
    "embracing",
    "empowering",
    "enabling",
    "engaging",
    "engineering",
    "enhancing",
    "evolving",
    "expediting",
    "exploiting",
    "extending",
    "fantasizing about",
    "facilitating",
    "fucking up",
    "generating",
    "growing",
    "harnessing",
    "implementing",
    "incentivizing",
    "incubating",
    "innovating",
    "integrating",
    "iterating",
    "leveraging",
    "matrixing",
    "maximizing",
    "meshing with",
    "mirroring",
    "monetizing",
    "morphing",
    "optimizing",
    "orchestrating",
    "productizing",
    "recontextualizing",
    "redefining",
    "reintermediating",
    "reinventing",
    "repurposing",
    "revolutionizing",
    "satirizing",
    "scaling",
    "seizing",
    "strategizing",
    "streamlining",
    "syndicating",
    "synergizing",
    "synthesizing",
    "targeting",
    "transforming",
    "transitioning",
    "unleashing",
    "utilizing",
    "visualizing",
    "whiteboarding"
  )

  private val adjectives = Array(
    "24/365",
    "24/7",
    "B2B",
    "B2C",
    "back-end",
    "best-of-breed",
    "bleeding-edge",
    "bricks-and-clicks",
    "clicks-and-mortar",
    "collaborative",
    "compelling",
    "cross-platform",
    "cross-media",
    "customized",
    "cutting-edge",
    "distributed",
    "dot-com",
    "dynamic",
    "e-business",
    "efficient",
    "end-to-end",
    "enterprise",
    "extensible",
    "frictionless",
    "front-end",
    "global",
    "granular",
    "holistic",
    "impactful",
    "innovative",
    "integrated",
    "interactive",
    "intuitive",
    "killer",
    "leading-edge",
    "magnetic",
    "mission-critical",
    "next-generation",
    "one-to-one",
    "open-source",
    "out-of-the-box",
    "plug-and-play",
    "proactive",
    "real-time",
    "revolutionary",
    "rich",
    "robust",
    "scalable",
    "seamless",
    "sexy",
    "sticky",
    "strategic",
    "synergistic",
    "transparent",
    "turn-key",
    "ubiquitous",
    "user-centric",
    "value-added",
    "vertical",
    "viral",
    "virtual",
    "visionary",
    "web-enabled",
    "wireless",
    "world-class"
  )

  private val nouns = Array(
    "action-items",
    "AI",
    "algorithms",
    "applications",
    "architectures",
    "bandwidth",
    "blogispheres",
    "channels",
    "cloud infrastructure",
    "communities",
    "content",
    "convergence",
    "deliverables",
    "experiences",
    "eyeballs",
    "infrastructures",
    "initiatives",
    "interfaces",
    "internet of things",
    "machine learning technologies",
    "markets",
    "methodologies",
    "metrics",
    "media",
    "mindshare",
    "models",
    "networks",
    "neural networks",
    "niches",
    "optimizations",
    "paradigms",
    "partnerships",
    "platforms",
    "portals",
    "relationships",
    "ROI",
    "synergies",
    "schemas",
    "solutions",
    "startups",
    "systems",
    "technologies",
    "users",
    "walled gardens",
    "web services"
  )

}
